"use client";

import { useState, useEffect } from "react";
import { Contract } from "ethers";
import type { JsonRpcSigner } from "ethers";

// ABI and addresses will be generated by genabi script
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let NoiseMonitorABI: any = { abi: [] };
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let NoiseMonitorAddresses: any = {};

try {
  NoiseMonitorABI = require("@/abi/NoiseMonitorABI").NoiseMonitorABI;
  NoiseMonitorAddresses = require("@/abi/NoiseMonitorAddresses").NoiseMonitorAddresses;
} catch (e) {
  console.warn("ABI files not generated yet. Run 'npm run genabi'");
}

export function useNoiseMonitor(signerPromise: Promise<JsonRpcSigner> | null, chainId: number | null) {
  const [contract, setContract] = useState<Contract | null>(null);
  const [address, setAddress] = useState<string | null>(null);

  useEffect(() => {
    if (!signerPromise || !chainId) {
      setContract(null);
      setAddress(null);
      return;
    }

    const addressInfo = NoiseMonitorAddresses[chainId.toString()];
    if (!addressInfo) {
      console.error(`NoiseMonitor not deployed on chain ${chainId}`);
      setContract(null);
      setAddress(null);
      return;
    }

    signerPromise
      .then((signer) => {
        const newContract = new Contract(addressInfo.address, NoiseMonitorABI.abi, signer);
        setContract(newContract);
        setAddress(addressInfo.address);
      })
      .catch((error) => {
        console.error("Failed to create contract instance:", error);
        setContract(null);
        setAddress(null);
      });
  }, [signerPromise, chainId]);

  return { contract, address };
}
